#ifndef DEVICEOPERATION_GLOBAL_H
#define DEVICEOPERATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEVICEOPERATION_LIBRARY)
#  define DEVICEOPERATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DEVICEOPERATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEVICEOPERATION_GLOBAL_H
